# Site settings
title:
header-img: img/logo.jpg
email: dfranco808@gmail.com
description: "Website being built for my summer internship"
baseurl: ""
url: "http://blog.algoritics.com"
twitter_username:
github_username:  Dmize1
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
